version: "3.8"
services:
## um banco mongo direto da imagem do docker.hub porem com volumes para ter persistência ,setamos os enviroment do banco e ultilizamos a porta 27017 com base na documentaçao 
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: max
      MONGO_INITDB_ROOT_PASSWORD: secret

## ##  criamos a image com base no dockerfiles dentro na pasta beackend apontamos para porta 80:80 (http)  ,criamos os volumes para persistência e  a envireoment do banco e setamos os depend para cria o beack com o banco somente
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    environment:
      MONGODB_USERNAME: max
      MONGODB_PASSWORD: secret
    depends_on:
      - mongodb

## criamos a image com base no dockerfiles ./frontend e ultizamos a porta 3000:3000 (tcp/ip) em locahost devido ser uma aplicaçao de fim educativo
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true

volumes: 
  data:
  logs:

